### ISSUE TITLE
Double Identification avec CasBundle

### ISSUE THREAD

**Issue by Aaarrrgggh** [l3-team/CasBundle#12]
Bonjour,

merci pour ce bundle ! 

j'ai installé le CasBundle sur une application Symfony 4. J'arrive bien à l'identification. 

J'aurai voulu savoir s'il était possible de paramétrer deux adresses CAS ? 

Puisqu'il n'y a qu'une config l3_cas possible, comment lui permettre l'identification via deux services possibles ? ex : monservice.identification.fr et mondeuxiemeservice.identification.fr ?

Auriez-vous une astuce ?

Merci pour votre retour

**Comment by mhetru** [comment]
Bonjour,
Je n’ai pas compris, vous avez plusieurs sites sur la même application? C’est ça? Des virtualhosts?

**Comment by Aaarrrgggh** [comment]
Bonjour,

non en fait, j'aimerai permettre l'identification sur l'application à partir de deux serveurs CAS. 

Concrètement, à partir d'une page "publique", l'utilisateur pourrait choisir de s'identifier soit à partir du serveur 1 cas.monserveur.fr soit à partir du serveur 2 cas2.monserveur.fr, selon son établissement d'origine. 

Est-ce possible à partir de votre bundle ?

**Comment by mhetru** [comment]
Non tel quel le bundle ne gère qu’un seul serveur cas dans sa configuration.

Mais rien ne vous empêche de construire le lien d’authentification manuellement pour forcer l’appel au serveur cas souhaité

Exemple :
 https://cas1.identification.fr/login?service=https://votreapplication.domain.fr
 https://cas2.identification.fr/login?service=https://votreapplication.domain.fr

**Comment by Aaarrrgggh** [comment]
D'accord, je vois, mais après comment vérifier que l'utilisateur est bien identifié et comment récupérer ses données (ex : nom, prénom, email ?) 

merci

**Comment by mhetru** [comment]
Désolé actuellement le bundle ne gère qu'un seul serveur cas.
J'ai même regardé les autres bundle symfony pour cas par exemple prayno et c'est pareil.
La seule solution serait que vous déployiez une deuxième fois l'application avec une autre config pour l'autre serveur cas.

**Comment by Aaarrrgggh** [comment]
Merci pour votre retour !

Malheureusement, j'aurai préféré ne pas déployer deux fois l'application, pour cause de coût, de maintenance, de suivi, etc. 

J'avoue que cette utilisation n'est pas commune :)
