### ISSUE TITLE
Questions a propos de CasListener

### ISSUE THREAD

**Issue by chippermcgee** [l3-team/CasBundle#13]
Bonjour monsieur,

Mon francais n'est pas si bon, et je ne sais pas comment faire des accents avec mon ordinateur, alors s'il vous plait me pardonnez des erreurs. Je m'expliquerai en Anglais apres tout.

Dans le CasListener, vous faisez ca:

        if ($this->getParameter('gateway')) {
            
            // .. code de pierre pelisset (pour les applis existantes...)
            
            if($this->getParameter('force')) {
                \phpCAS::forceAuthentication();
                $force = true;
            } else {
                $force = false;
                 ...
            }
            if(!$force) {
                ...
            }
            
        } else { 
            if($this->getParameter('force')) {
                \phpCAS::forceAuthentication();
            } else {
                      ...
            }
        } 

Et finalement a la fin de l'action, vouz essayez de creer un token et le mettre dans le TokenStorage avec les resultats de forceAuthentication().

Est-ce que ce serait plus facile de verifier le parametre `force` avant verifier le parametre `gateway`? Ce semble que les deux parametres sont independant. Vous faisez le meme chose pour `force`, si `gateway` est vrai et si c'est faux. Si vous verifiez le parametre `force` avant le parametre `gateway`, il n'y aura pas besoin de utiliser le variable booleen `$force`, parce que si vous etez arrive (c'est le passe compose, ici) dans le code pour verifier `gateway`, vouz savez que le parametre `force` est faux.

Ce ne donnera pas les memes resultats?

En Anglais, maintenant:

You do the same thing for the "force" parameter regardless of whether or not "gateway" is true, and "force" does not influence what you do in the "gateway" parameter logic (other than the $force boolean, which wouldn't be needed if you separated the verification of "force"). Would separating the two checks (first "force", then "gateway") not give the same results?

**Comment by chippermcgee** [comment]
Pardonnez-moi, si ca marche, ce n'est pas un erreur.

**Comment by mhetru** [comment]
Bonjour,
Je pourrais mieux faire oui mais c’est code historique utilisé déjà dans des applications...
Donc je laisse le code dans le bundle.
Cordialement.
