### ISSUE TITLE
Automatically add users at login

### ISSUE THREAD

**Issue by moobyfr** [l3-team/CasBundle#14]
Is there a way to add automatically an entry for a User (my provider is FOSUser) when a user log-in ?

**Comment by mhetru** [comment]
Sorry perhaps it is possible but on settings of fosuserbundle.

**Comment by mhetru** [comment]
here is the documentation : https://symfony.com/doc/master/bundles/FOSUserBundle/index.html
if you found, i am interested

**Comment by Lubna93** [comment]
@moobyfr Hello!! Did you find a way to do that? Very interested too :)
Thanks!
