### ISSUE TITLE
Clarification request

### ISSUE THREAD

**Issue by drupol** [l3-team/CasBundle#16]
Hi,

Thanks for this bundle, I will have to try it soon.

I have a simple request, I would like to understand why the [GuardAuthenticator](https://symfony.com/doc/current/security/guard_authentication.html) is not used to do the authentication.
What are the benefit of not using it against using it in this particular case (CAS authentication).

Thanks :-)

**Comment by mhetru** [comment]
It si historical, because i start write the bundle with version 2.6 of symfony.. And guard authenticator is a feature since symfony version 3.0

**Comment by drupol** [comment]
Oooh ok, there is no technical reason behind then.

If you had to rewrite it for Symfony 3, would you then use the GuardAuthenticator for this ?

Thanks.

**Comment by mhetru** [comment]
At this moment it is compatible with last symfony. There is no technical reason to rewrite with guard authenticator. If it works, don’t fix it ;-)

**Comment by mhetru** [comment]
hello i'm re-writing the bundle in guard authenticator mode in order to port the compatibility with Symfony 6

**Comment by drupol** [comment]
Yep, me too with cas-bundle: https://github.com/ecphp/cas-bundle/pull/59

**Comment by drupol** [comment]
How about unifying our forces and make one single bundle? Have you checked https://github.com/ecphp/cas-lib/ which basically does the heavy lifting for you already.

**Comment by mhetru** [comment]
avec plaisir pour un travail d'équipe. pour moi, je maintiens le bundle l3/cas-bundle et l3/cas-guard-bundle à présent pour des besoins professionnels car il est utilisé dans beaucoup d'applications dans mon job

**Comment by mhetru** [comment]
With pleasure for teamwork. for me, i keep the l3/cas-bundle and l3/cas-guard-bundle now for professional purposes because it is used in a lot of applications in my job

**Comment by drupol** [comment]
That's a great news already ! How about starting by testing https://github.com/ecphp/cas-lib in your own bundle?

Keeping your bundle is perfectly fine, the idea is to use the same library for handling the CAS protocol.

Let me know if I can be of any other help.

Cheers.
