### ISSUE TITLE
switch_user

### ISSUE THREAD

**Issue by mattbild** [l3-team/CasBundle#18]
bonjour,
je mets en place une nouvelle appli SF4.4 avec votre bundle pour authentification CAS.
Cette partie fonctionne très bien mais je rencontre un souci avec le switch_user. Je ne sais pas si c'est lié... 
Si mon utilisateur n'a pas le droit d'appeler l'url, je ne fais jeter.
Si l'utilisateur que je passe en paramètre n'existe pas dans ma base de données (selon mon user_provider), je ne fais jeter.
Donc tout semble être bien vérifié, sauf que je ne switch pas. La page est rafraîchi avec mon user de base.
Avez-vous une idée de ce qui peut coincer s'il vous plaît ?

**Comment by mhetru** [comment]
Bonjour,
je possède un système de switch et je ne rencontre aucun pb.
il faudrait que vous traciez les variables utilisées par votre système de switch dans les logs (LoggerInterface) car il doit y avoir un pb dans votre système de switch.
Bonne journée.
Cordialement.
