### ISSUE TITLE
erreur avec phpcas 1.3.9

### ISSUE THREAD

**Issue by jcgriebel** [l3-team/CasBundle#19]
Bonjour,
une nouvelle version du PHPCAS vient de sortir (version 1.3.9)
elle génère une erreur "phpCAS::client(): ErrorException: Warning: session_set_save_handler(): Cannot change save handler when session is active"
La version 1.3.8 elle fonctionne toujours.
je ne sais pas si le correctif est à fait du coté CasBundle ou bien si il faut attendre un Fix de la version 1.3.9

**Comment by Robszyy** [comment]
Bonjour @jcgriebel,

L'erreur a été signalée au près de [phpCas](https://github.com/apereo/phpCAS/issues/365)
En attendant le correctif, on peut [bypass l'erreur](https://github.com/apereo/phpCAS/issues/365#issuecomment-772434032)
En espérant que ça t'aide.

**Comment by mhetru** [comment]
Bonjour @jcgriebel,

Vous rencontrez toujours le problème ?

**Comment by jcgriebel** [comment]
Oui le problème est toujours la.

**Comment by jcgriebel** [comment]
Je corrige le problème est corrigé sur la version dev-master.

**Comment by mhetru** [comment]
Ca serait quoi le mieux ? de baser casbundle sur la version 1.3.8 de phpcas ? ou on patiente que phpcas va corriger son code pour la version 1.3.9 ?

**Comment by jcgriebel** [comment]
Normalement  une fois que le correctif sera validé ils livreront un fix de la version 1.3.9.
Dans ce type de situation il faut attendre le fix et rester sur la 1.3.8

**Comment by mhetru** [comment]
Vous pouvez downgrader le paquet jasig 1.3.9 d'installé avec cette commande :

> composer require jasig/phpcas:1.3.8

**Comment by mhetru** [comment]
Bonjour le phpcas 1.3.9 a été corrigé ?

**Comment by mhetru** [comment]
Bonjour j'ai mis 1.3.8 dans le composer.json
