### ISSUE TITLE
Compatiblité php 8

### ISSUE THREAD

**Issue by likou31** [l3-team/CasBundle#20]
Bonjour !

Je ne suis pas très à l'aide avec la création de bundle tout ça, et j'ai besoin d'un bundle pour une connexion CAS. J'ai trouvé le votre, sauf que je suis sur les denières versions de Symfony et PHP.
Serait-il possible de mettre à jour le composer.json afin le rendre compatible avec la version 8 de PHP et 5.2 de symfony svp ? (Car en essayant de fork, je ne sais pas comment l'installer avec composer à partir de mon repo...)

**Comment by mhetru** [comment]
Bonjour j'ai modifié le composer.json pour mettre >=7.2.5 donc pour php 8 ce sera ok.
J'ai modifié la branche master, et la branche sf5.x et republié le tag 1.1.14 de packagist.org.
Je vous invite à mettre à jour votre projet avec commande suivante : 
`composer update l3/cas-bundle --prefer-source`
Dites moi si c'est ok pour vous.
Cordialement.

**Comment by likou31** [comment]
Bonjour ! Merci pour votre aide ! Finalement j’ai reussi a installer en utilisant l’option pour installer sans avoir besoin des dependances et ça marche nickel ! Du coup j’ai pu utiliser le bundle qui est fonctionnel ! Merci !
