### ISSUE TITLE
FosRestApi Symfony and cas firewall

### ISSUE THREAD

**Issue by habib-halaoui** [l3-team/CasBundle#22]
I have a web application which uses for the react js front part and the symfony backend and a cas sso authentication server.
I have configured react to authenticate with case and the backend part also configured with case. The user is authenticated on both applications. But the problem that I can not use the api rest of the backend because it is not recognized that it is connected to because via axios http requests.
I saw that it was necessary to set up a proxy case.
Do you have any information on this use case and how to do it?
Does your example take into account the proxy case?
This link details the API call in case.
https://apereo.github.io/cas/5.0.x/installation/Configuring-Proxy-Authentication.html
Regards

**Comment by mhetru** [comment]
Hello, can you test with CAS_GATEWAY=false in your config file ?
