### ISSUE TITLE
Cannot configure AuthenticatorManager as "cas" authentication does not support it, 

### ISSUE THREAD

**Issue by jcgriebel** [l3-team/CasBundle#24]
Bonjour,
nous avons besoin de faire une double authentification Formulaire et CAS
avec synfony 5.3 il y a le paramètre "enable_csrf: true" qui demande d'activer l'authenticator manager
security:
    # you must use the authenticator manager
    enable_authenticator_manager: true

Or nous avons un messagd d'erreur qui dit que le bundle cas n'est pas compatible.

Cannot configure AuthenticatorManager as "cas" authentication does not support it, set "security.enable_authenticator_manager" to `false`.

y a t'il un moyen de le rendre compatible ?
Merci.

**Comment by mhetru** [comment]
Bonsoir, j'ai codé une version pour symfony 5 de l3/cas-bundle mais également une version pour symfony 6 mais dans un autre bundle il s'agit de l3/cas-guard-bundle
