### ISSUE TITLE
User Deprecated: phpCAS::setDebug() is deprecated in favor of phpCAS::setLogger()

### ISSUE THREAD

**Issue by acardielwata** [l3-team/CasBundle#25]
I'm getting this output log message using version 1.1.11 (latest version allowed for a SF 3.4):

php.INFO: User Deprecated: phpCAS::setDebug() is deprecated in favor of phpCAS::setLogger(). {"exception":"[object] (ErrorException(code: 0): User Deprecated: phpCAS::setDebug() is deprecated in favor of phpCAS::setLogger(). at [...]/vendor/jasig/phpcas/source/CAS.php:470)"} []

Used in Security/CasListener.php:28

**Comment by mhetru** [comment]
hello i have modified composer.json for version of phpcas at 1.3.8
