### ISSUE TITLE
Symfony 6.0 compatibility

### ISSUE THREAD

**Issue by Lubna93** [l3-team/CasBundle#27]
Hello, many thanks for your great efforts! Really appreciate your time and your helpful bundle :)
I am wondering if I can use this CAS bundle for Symfony 6 for now?

Thank you again!

**Comment by mhetru** [comment]
Hello, thanks, it is coming soon, i am rewriting the code of the bundle with guard mode here : https://github.com/l3-team/CasGuardBundle and https://packagist.org/packages/l3/cas-guard-bundle

**Comment by Lubna93** [comment]
Hi again,
Sorry if I am bothering you. I have a question I don't know where excactly the problem. I am gonna show you below my code maybe you can help me. Thank you very much in advance!

**Comment by Lubna93** [comment]
Hi again!

I would be grateful if you can take a look at my **.env** and let me know if it's ok because it still doesn't work with me and my project deadline is this afternoon:

```
###> l3/cas-bundle ###
CAS_HOST=casv3.univ-montp3.fr/casv3     # Cas Server
CAS_PATH=             # App path if not in root (eg. cas.test.com/cas)
CAS_PORT=443                         # Server port
CAS_CA=false                         # SSL Certificate
CAS_HANDLE_LOGOUT_REQUEST=false       # Single sign out activation (default: false)
CAS_LOGIN_TARGET=https://localhost:8000/admin # Redirect path after login (when use anonymous mode)
CAS_LOGOUT_TARGET=https://casv3.univ-montp3.fr/casv3/logout    # Redirect path after logout
CAS_FORCE=false                       # Allows cas check mode and not force, user : __NO_USER__ if not connected (If force false, Single sign out cant work).
CAS_GATEWAY=false		     # Gateway mode (for use the mode gateway of the Cas Server) set to false if you use micro-services or apis rest.
###< l3/cas-bundle ###
```

Many thanks in advane!

**Comment by mhetru** [comment]
Est ce si tu mets /casv3 dans CAS_PATH au lieu de le mettre dans CAS_HOST tu as du mieux ?

**Comment by mhetru** [comment]
Par contre la config c’est dans le fichier .env.local et pas .env car .env est gitté

**Comment by Lubna93** [comment]
Hello, many thanks for your quick responce. Thanks a million.

I still have some problems like this message:

> An exception has been thrown during the rendering of a template ("Unable to find the current firewall LogoutListener, please provide the provider key manually.").

Can I show you my security code if I don't bother you?

```
security:
    enable_authenticator_manager: false
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # users_in_memory: { memory: null }
        uid:
            id: uid_user_provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        l3_firewall:
            pattern: ^/
            security: true
            cas: true # Activation du CAS

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
```
If i replaced **l3_firewall:** with main as below I can login but there is no auth on the redirect page: 
```
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: users_in_memory
```

Sorry again and again and many thanks for your help and support!

**Comment by Lubna93** [comment]
Merci bcp encore! I think i found the solution here:
https://github.com/EasyCorp/EasyAdminBundle/pull/1571/commits/2d552faa5b5820c6b911211a4b0cabab9823ba0c

Bonne journée ! ^^

**Comment by mhetru** [comment]
C’était quoi le souci ?

**Comment by Lubna93** [comment]
Hello again :)
I added the following line `\phpCAS::setVerbose(true);` in **CasListener.php** file
between `\phpCAS::setDebug(false);` and `\phpCAS::client(`


Then I added **logout path** in **Security.yaml** file.

Right now i can log in but can't logout :'(

**Comment by mhetru** [comment]
Logout path in security.yaml??

it just a controller.. why you add it in security.yaml?

**Comment by Lubna93** [comment]
To be honest, i got received this message:
>  ("Unable to find the current firewall LogoutListener, please provide the provider key manually.")

So I thought I should create it in Security.yaml
Maybe because I use EasyAdmin?

**Comment by mhetru** [comment]
Which version you use for symfony ?

**Comment by Lubna93** [comment]
Many thanks for your reply! I use version 5.4

**Comment by mhetru** [comment]
CAN you send your application zipped to my mail ? (See it it composer.json) remove your passwords. I will see it

**Comment by Lubna93** [comment]
It's very nice of you and I can't thank you enough! Could you please provide me with your email?

**Comment by mhetru** [comment]
You can find my mail univ in composer.json (mathieu hetru)

**Comment by Lubna93** [comment]
Many thanks! Email has been sent yesterday and sorry because i have sent it on the weekend but I totally forgot that! Sorry again.

**Comment by Lubna93** [comment]
Hi again! Sorry if I am bothering you or I ask for too much! Really sorry.
I am wondering if I missed  something like adding (use statement) or adding something additional in the framework.yaml file as below:
```
    session:
        handler_id: ~
        save_path: ~
```
Also, I can speak French (I'm not native) if you would prefer to text me in French.

Thanks again!

**Comment by mhetru** [comment]
Hello, can you send me the dump of your database ? because i cannot test your code

**Comment by Lubna93** [comment]
Issue resolved with a million thanks! ^^
