### ISSUE TITLE
Switch_user et Login_form

### ISSUE THREAD

**Issue by lemairep** [l3-team/CasBundle#3]
Bonjour,
Je viens d'essayer votre bundle pour l'intranet de notre lycée avec succès (Symfony 3.2), merci.
Il me reste deux problèmes à régler 
    - Est ce possible d'utiliser votre bundle en parallèle du login form dans security.yml (même provider, même firewall). Le but est d'avoir une connexion CAS et un fallback sur le login_form en cas de failure.
    - Implanter switch_user, cela ne semble pas fonctionner pour l'instant. 
       si je fais http://127.0.0.1:8000/accueil?_switch_user=leuser le user est bien basculé à leuser puis je suis redirigé (intercept_redirects: true) vers la page accueil ... et repassé en admin :c/

D'avance merci pour tout aide
Philippe

**Comment by mhetru** [comment]
Bonjour,
Oui vous pouvez utiliser la methode chain_provider pour cumuler plusieurs userprovider possibles.
- voir : http://symfony.com/doc/current/security/multiple_user_providers.html
- regardez aussi comment a fait un utilisateur pour utiliser le fosuserbundle avec le casbundle en utilisant le chain_provider vous pourrez vous en inspirer : https://github.com/l3-team/CasBundle/issues/2
Est-ce que ca répond à votre question?
Cordialement.

**Comment by mhetru** [comment]
Bonjour,
Avez-vous résolu votre problème?
Cdt

**Comment by lemairep** [comment]
Bonjour
Désolé de n'avoir pas répondu avant, je travail sur ce projet sur mon temps libre et c'est chose rare ces temps ci..
Malheureusement votre proposition ne répond pas vraiment à mon problème. Actuellement je n'ai qu'un seul provider (une entité User) avec tous les utilisateurs.
Il faut que je remette à plat mon architecture au niveau de l'authentification. Je pense que je fais fausse route.
Je suis à la recherche de conseil, seriez vous d'accord, si je vous envois une description de mon projet par email (pour ne pas polluer), de me dire ce que vous en pensez ?
Cordialement

**Comment by mhetru** [comment]
oui bien sûr écrivez moi sur ipsykozi_AT_gmail.com
