### ISSUE TITLE
Symfony needs %cas% quoted

### ISSUE THREAD

**Issue by smcjones** [l3-team/CasBundle#5]
First of all, thanks for this bundle. It works better than any of the others and I am very happy with it.

Second of all, just as a heads up, I'm getting nag warnings that in services.yml you will need to quote %cas% (like "%cas%") or this will not be compatible with Symfony 4.

Thanks!

Sean

**Comment by mhetru** [comment]
Where have you download symfony 4?

I will test :-)

Thanks!

**Comment by smcjones** [comment]
This is a deprecation notice on Symfony 3.3, that as of Symfony 4 unquoted variables will trigger an error.

Thanks,

Sean

**Comment by mhetru** [comment]
Thanks! i will correct it, but i wait the version 3.4 before

**Comment by mhetru** [comment]
i have tested with symfony 3.3 but i got not your deprecation notice.
are you sure that you use 3.3 or it is the 3.4 beta ?

**Comment by db4y** [comment]
@mhetru see http://symfony.com/blog/new-in-symfony-3-1-yaml-deprecations

**Comment by mhetru** [comment]
thanks
can you test your application after made "composer update" ? please :)

**Comment by smcjones** [comment]
Yes appears to be fine on my end... No further action needed on your part! Closing ticket.
