### ISSUE TITLE
Add minimum version to Symfony 4?

### ISSUE THREAD

**Issue by smcjones** [l3-team/CasBundle#6]
Any chance of upping the version in `composer.json` to enable Symfony 4.~?

Thanks,

Sean

**Comment by mhetru** [comment]
yes, you can test and make a PR if you want ;)
just dev in your vendor folder before make a PR

**Comment by smcjones** [comment]
There were a few issues I had to parse through but I believe it is up-to-date and still backwards compatible. I will submit a PR soon for your review.

Thanks!

**Comment by mhetru** [comment]
i have released a version of the bundle for symfony 4.0.
have fun!
you can close here ;)
