### ISSUE TITLE
Switch to Open Source licence?

### ISSUE THREAD

**Issue by anthony-o** [l3-team/CasBundle#9]
Would you be able to switch to an Open Source licence for this project please? (MIT, *GPL, Apache, etc)

This could encourage people to participate to this project :)

**Comment by mhetru** [comment]
i have requested my director at my job in University and he answers : "yes you can change the license for GPL-3.0 if you notice 'Université Lille 3 - Charles de Gaulle' in the README"

**Comment by anthony-o** [comment]
Great ! As it's a library, I advice you to choose LGPL-3.0 because else it will force people who want to use this library to switch their entier project to GPL-3.0 also...
